deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/ConfigurationServiceBuildItem.java, deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java, integration-tests/src/main/resources/application.properties, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeOperatorConfiguration.java
=> feat: make number of reconciliation threads configurable

deployment/pom.xml, integration-tests/pom.xml, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/AbstractController.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/DelayedController.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/TestController.java, integration-tests/src/main/resources/application.properties, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java, pom.xml, runtime/pom.xml, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/DelayRegistrationUntil.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeOperatorConfiguration.java, samples/pom.xml
- Update JOSDK to 1.9.0
- Update fabric8 client to 5.4.1
- Fix several issues
=> Improvements

deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, pom.xml, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ClassUtils.java, runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java
=> Opt in regular reflection registration for CustomResource children instead of weak version

.github/workflows/release.yml
=> Indicate the branch when pushing the tags

integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/CustomKubernetesServerTestResource.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java, pom.xml
Note that this will work only with fabric8 5.10+
=> feat: configure mock server

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRoleBindingDecorator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRoleDecorator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddRoleBindingsDecorator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
=> Fix RBAC generation

.github/project.yml
- chore(deps): bump josdk to 1.10.2
- chore: release 2.0.3
=> release 2.0.3

samples/README.md
* Parent project must be installed 
Adding step to build and install parent project locally.
=> [PR] Add step to install parent project locally (#1)

samples/pom.xml, samples/src/main/java/io/quarkiverse/operatorsdk/samples/joke/JokeService.java, samples/src/main/resources/application.properties, samples/src/test/java/io/quarkiverse/operatorsdk/samples/joke/JokeReconcilerTest.java
=> test: add integration tests to joke sample

common/src/main/java/io/quarkiverse/operatorsdk/common/ClassUtils.java, common/src/main/java/io/quarkiverse/operatorsdk/common/Constants.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusDependentResourceConfiguration.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusKubernetesDependentResourceConfiguration.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusKubernetesDependentResourceController.java
=> feat: initial support for dependent resources

samples/pom.xml, samples/src/main/java/io/quarkiverse/operatorsdk/samples/joke/JokeService.java
RESTEasy Reactive provides much better runtime footprint
than RESTEasy Classic and is the preferred REST stack now
in Quarkus
=> Use RESTEasy Reactive in sample

.github/project.yml, bom/pom.xml
- chore(deps): update to JOSDK 2.1.1
- chore: release 3.0.3 (for real this time!)
=> release 3.0.3

.github/project.yml, bom/pom.xml, build-parent/pom.xml
- chore(deps): upgrade to Quarkus 2.7.3
- chore: release 3.0.4
=> release 3.0.4

.github/workflows/release.yml, .github/workflows/snapshot-release.yml, pom.xml, samples/pom.xml
- fix: do not release integration-tests or samples
- feat: exclude integration tests and samples from snapshot release
- fix: exclude integration tests from default profile
- fix: skip deploying and signing of samples
=> project maintenance

bom/pom.xml, build-parent/pom.xml, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/ContextStoredControllerConfigurations.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusDependentResourceSpec.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusKubernetesDependentResourceConfig.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/AbstractReconciler.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/CRUDDependentResource.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/DependentDefiningReconciler.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/ReadOnlyDependentResource.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/ShouldBeIgnoredReconciler.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java, samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/SchemaPollingResourceSupplier.java
- feat: support changes from latest SDK
- fix: actually do not require changes in JOSDK
- refactor: use resource class directly
- refactor: better encapsulation of decision to generate config
- chore: update to latest JOSDK
- chore: add dependent tests
- chore: update to Quarkus 2.7.4
- fix: add proper accessors so that buildable constructor can work
- fix: ResourceSupplier -> ResourceFetcher
=> feat: update to latest SDK

.github/project.yml, bom/pom.xml
- chore: update to JOSDK 2.1.2
- chore: release 3.0.5
=> release 3.0.5

bom/pom.xml, samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/dependent/SecretDependentResource.java
- chore: update to Fabric8 client 5.12.2
- fix: adapt for JOSDK API changes
=> chore: updates

bom/pom.xml, build-parent/pom.xml, bundle-generator/deployment/pom.xml, bundle-generator/pom.xml, bundle-generator/runtime/pom.xml, common-deployment/pom.xml, common/pom.xml, core/deployment/pom.xml, core/pom.xml, core/runtime/pom.xml, integration-tests/pom.xml, pom.xml, samples/exposedapp/pom.xml, samples/joke/pom.xml, samples/mysql-schema/pom.xml, samples/pingpong/pom.xml, samples/pom.xml
=> chore: update version to 4.0.0-SNAPSHOT

docs/modules/ROOT/pages/index.adoc, samples/joke/README.md
Fix https://github.com/quarkiverse/quarkus-operator-sdk/issues/245
=> docs: add documentation about how to deploy operators into the docs

bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/DefaultBundleWhenNoCsvMetadataTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
- chore: prepare 4.0.0.Beta1 release
- fix: disable tests for release until a proper solution can be found
=> release 4.0.0.Beta1

.github/workflows/release.yml, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/DefaultBundleWhenNoCsvMetadataTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
Fix https://github.com/quarkiverse/quarkus-operator-sdk/issues/320
=> fix: skip tests during release

bom/pom.xml, build-parent/pom.xml, pom.xml, samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/MySQLSchemaReconciler.java, samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/dependent/SchemaDependentResource.java
In the reconciler, if the secret is not yet ready, an event should be fired when it will be the case.
The reconciler should not throw on purpose to retry but let new events the opportunity to reconcile
=> Fix for josdk 1179

.github/project.yml, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/BuildTimeHybridControllerConfiguration.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, pom.xml
- chore: update to JOSDK 3.0.0.RC5
- chore: release 4.0.0.Beta2
=> chore: release 4.0.0.Beta2

samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/MySQLSchemaReconciler.java
=> test(mysql-schema): remove Cleaner interface

common/src/main/java/io/quarkiverse/operatorsdk/common/ClassUtils.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/TestReconciler.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
- feat: add instantiate method
- fix: add support for event filters and max reconciliation interval
=> fix: add support for event filters and max reconciliation interval

common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ConfigurationUtils.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/NativeOperatorSDKResourceIT.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java, pom.xml, samples/exposedapp/src/main/java/io/halkyon/IngressDependent.java, samples/exposedapp/src/main/java/io/halkyon/ServiceDependent.java, samples/exposedapp/src/test/java/io/halkyon/ExposedAppReconcilerTest.java
Requires quarkusio/quarkus#26107
=> chore: update to JOSDK 3.2 & fabric8 client 6.1, pending Quarkus update

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/AppEventListener.java
=> fix: delay operator start until after application-level events

.github/workflows/build-for-quarkus-version.yml, .github/workflows/build.yml, core/deployment/pom.xml, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java, pom.xml
Requires java-operator-sdk/java-operator-sdk#1493
=> feat: inject leader election / informer stopped handler into config

integration-tests/pom.xml
@metacosm this will be enough to be integrated in the platform
=> Publish test-jars

.github/project.yml, .github/workflows/build.yml, pom.xml
- chore: get ready for 4.0.4 release
- chore: update to Quarkus 2.13.3
=> chore: update to Quarkus 2.13.3 and JOSDK 3.2.4

common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ResourceAssociatedAugmentedClassInfo.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java
- fix: only generate all CRD if we should generate CRDs at all
- fix: use proper logger as it is less confusing
- fix: reconciler info also returns associated CR info for reflection
=> fix: properly register reconciler-associated classes for reflection

.github/project.yml
Beta release for inclusion in Quarkus platform: see quarkusio/quarkus-platform#673
=> chore: prepare for 5.0.0.Beta1 release

core/deployment/pom.xml, core/runtime/pom.xml, docs/modules/ROOT/pages/index.adoc, samples/joke/pom.xml, samples/pingpong/pom.xml
=> chore: remove JIB dependency

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusManagedWorkflow.java
- feat: disable leader election when in dev mode
- chore: adapt to latest SNAPSHOT
=> disable leader election dev mode

.github/project.yml, .github/workflows/build.yml, pom.xml
- chore: update Quarkus to 2.15.1
- chore: prepare 5.0.2 release
=> chore: update Quarkus to 2.15.1.Final

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/CRUDDependentResource.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/DependentDefiningReconciler.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/ReadOnlyDependentResource.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java, samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/dependent/SchemaDependentResource.java
=> fix: properly configure DependentResources after creating them

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, integration-tests/src/main/resources/application.properties, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
=> fix: retry should properly be reset when configuration changes

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java, pom.xml, samples/exposedapp/src/main/resources/application.properties, samples/exposedapp/src/test/java/io/halkyon/ExposedAppReconcilerTest.java
=> fix: it should now be possible to restart the operator

.github/project.yml, .github/workflows/build-for-quarkus-version.yml, .github/workflows/build.yml, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/Keycloak.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/KeycloakController.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/CustomKubernetesServerTestResource.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java, pom.xml
- chore: update to Quarkus 2.13.6.Final
- chore: prepare release 4.0.6
=> chore: upgrade Quarkus to 2.13.6.Final

bom/pom.xml, build-parent/pom.xml, bundle-generator/deployment/pom.xml, bundle-generator/pom.xml, bundle-generator/runtime/pom.xml, common-deployment/pom.xml, common/pom.xml, core/deployment/pom.xml, core/deployment/src/main/java-templates/io/quarkiverse/operatorsdk/deployment/Versions.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, core/pom.xml, core/runtime/pom.xml, core/runtime/src/main/java-templates/io/quarkiverse/operatorsdk/runtime/Versions.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeOperatorConfiguration.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/Version.java, integration-tests/pom.xml, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/ReadOnlyDependentResource.java, pom.xml, samples/exposedapp/pom.xml, samples/exposedapp/src/main/java/io/halkyon/IngressDependent.java, samples/joke/pom.xml, samples/mysql-schema/pom.xml, samples/pingpong/pom.xml, samples/pom.xml
- Implement a compile time check of the Quarkus version
- Fix dynamic version retrieval
- Conditional failure
- Commented out fabric8 check
- fmt
=> feat: build time check of versions alignment

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/CRUDConfigMap.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/CreateOnlyService.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/Foo.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/NonKubeResource.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/ReadOnlySecret.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/SimpleCR.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/SimpleReconciler.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/SimpleSpec.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/SimpleStatus.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/TestCR.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/TestReconciler.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/DependentResourceSpecMetadata.java
=> feat: use dependent information to generate RBACs

.github/workflows/build-for-quarkus-version.yml, common/src/main/java/io/quarkiverse/operatorsdk/common/RuntimeConfigurationUtils.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/BuildTimeHybridControllerConfiguration.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, integration-tests/pom.xml, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/NameWithSpaceReconciler.java, integration-tests/src/main/resources/application.properties, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/CustomKubernetesServerTestResource.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
=> fix: properly support overriding from environment variables

.github/project.yml, pom.xml
- chore: update to JOSDK 4.2.3
- chore: prepare for 5.0.3 release
=> chore: update to JOSDK 4.2.3

.github/workflows/build-for-quarkus-version.yml
(cherry picked from commit e26b30b1aecda7717e0a80c4cf7bd5189cd31ff0)
=> chore: remove now unneeded passing of env variables

.github/project.yml, pom.xml
- chore: update JOSDK to 4.2.8
- chore: update quarkiverse-parent
- chore: prepare 5.1.1 release
=> chore: release 5.1.1

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
=> fix: make CRD order predictable in CSV

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java
=> feat: make it possible to inject the Operator in Reconcilers

.github/scripts/installOperatorUsingOlm.sh, .github/scripts/testJokeSample.sh, .github/scripts/testPingPongSample.sh, .github/scripts/waitFor.sh, .github/workflows/build-for-quarkus-version.yml, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddRoleBindingsDecorator.java
=> Fix cycle decorator in Dekorate

.github/scripts/installOperatorUsingOlm.sh, .github/scripts/testJokeSample.sh, .github/scripts/testPingPongSample.sh, .github/scripts/waitFor.sh, .github/workflows/build-for-quarkus-version.yml, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddRoleBindingsDecorator.java
- make sure that failures do fail the build
- improve logging
- update to more recent OLM to fix issue with KinD
=> fix: improve and fix OLM-related CI

.github/project.yml, .github/workflows/build.yml, pom.xml
- chore: update to Quarkus 2.16.6
- chore: release 5.1.4
=> quarkus 2.16.6

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleGenerator.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/AnnotationsManifestsBuilder.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/BundleDockerfileManifestsBuilder.java
=> feat: order labels

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
This allows users to provide their own implementation if needed.
=> feat: make recorded ConfigurationService a default bean

docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, pom.xml
Hey there,
Here is a PR to update to Quarkus 3.0.0.Final.
It would be nice if you could merge it and release a new major version before April 25th so that it's ready for the announcement.
Please ping me when the release is done so that I can include it in our automatic update recipes.
Thanks!
=> Upgrade to Quarkus 3.0.0.Final

bundle-generator/runtime/src/main/resources/META-INF/quarkus-extension.yaml, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/devui/DevUIProcessor.java, core/deployment/src/main/resources/dev-ui/qwc-qosdk-controllers.js, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/devconsole/ControllerInfo.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/devconsole/ControllersSupplier.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/devconsole/DependentInfo.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/devconsole/EventSourceInfo.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/devui/JSONRPCService.java, core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
=> feat: support new Dev UI

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
=> feat: activate Quarkus-provided client version check

.github/project.yml, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleGenerator.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/VersionBuildItem.java
=> feat: add metrics bundle annotations, fix wrong version handling

.github/workflows/build-for-quarkus-version.yml, .github/workflows/build.yml, .github/workflows/nightly-build-with-f8-snapshot.yml, .github/workflows/snapshot-release.yml
- feat: enable specifying which branch to build
- feat: automatically pick up latest quarkus version
=> fix: properly enable nightly builds

.github/project.yml, .github/workflows/release.yml, docs/modules/ROOT/pages/includes/attributes.adoc
- chore: revert release 6.0.3
- fix: do not release samples or run tests while releasing
=> chore: revert release 6.0.3

pom.xml
=> fix: add maven central repositories to let dependabot know about them

.github/project.yml, bom/pom.xml, build-parent/pom.xml, bundle-generator/deployment/pom.xml, bundle-generator/pom.xml, bundle-generator/runtime/pom.xml, common-deployment/pom.xml, common/pom.xml, core/deployment/pom.xml, core/pom.xml, core/runtime/pom.xml, docs/modules/ROOT/pages/includes/attributes.adoc, docs/pom.xml, integration-tests/pom.xml, pom.xml, samples/exposedapp/pom.xml, samples/joke/pom.xml, samples/mysql-schema/pom.xml, samples/pingpong/pom.xml, samples/pom.xml
- chore: change version to 6.1.0-SNAPSHOT
- chore: update to Quarkus 3.1.0
- chore: update to JOSDK 4.3.5
- chore: release 6.1.0
=> chore: update to Quarkus 3.1.0 & JOSDK 4.3.5

.github/project.yml, .github/workflows/build.yml, pom.xml
=> chore: update to Quarkus 2.13.8

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/DefaultBundleWhenNoCsvMetadataTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/PodDependentResource.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/ThirdReconciler.java, common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ReconciledResourceAugmentedClassInfo.java
- refactor: improve logging message
- refactor: use existing constant
- feat: properly output dependent native APIs
=> feat: properly output dependent native APIs

.github/project.yml, .github/workflows/build.yml, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/DefaultConfigurationTest.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/KubernetesClientSerializationCustomizerTest.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeOperatorConfiguration.java, docs/modules/ROOT/pages/includes/attributes.adoc, docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
- test: re-enable test that should now be passing
- docs: improve documentation for operator-level namespaces property
=> docs: improve documentation for operator-level namespaces property

.github/workflows/release.yml
=> fix: also update QOSDK version in memcached operator

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/AppEventListener.java
=> fix: do not automatically stop Operator when it wasn't started automatically either

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddRoleBindingsDecorator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/BuildTimeHybridControllerConfiguration.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuildStep.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java, core/deployment/src/test/resources/application.properties, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeOperatorConfiguration.java, docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, integration-tests/src/main/resources/application.properties
=> feat: allow specifying operator-level namespaces to generate manifests

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java
this is needed when it is created by SSA
=> fix: add patch for creator dependent resource role

common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ClassUtils.java, common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/CustomResourceAugmentedClassInfo.java, common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ReconciledResourceAugmentedClassInfo.java, common-deployment/src/test/java/io/quarkiverse/operatorsdk/common/ClassUtilsTest.java
=> fix: status detection in non-CR resources

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, integration-tests/src/main/resources/application.properties, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/EmptyOperatorLevelNamespacesTest.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/EmptyOperatorLevelNamespacesTestProfile.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/SetOperatorLevelNamespacesTest.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/SetOperatorLevelNamespacesTestProfile.java
=> fix: trim namespaces when setting them, add more tests

.github/project.yml, bom/pom.xml, build-parent/pom.xml, bundle-generator/deployment/pom.xml, bundle-generator/pom.xml, bundle-generator/runtime/pom.xml, common-deployment/pom.xml, common/pom.xml, core/deployment/pom.xml, core/pom.xml, core/runtime/pom.xml, docs/modules/ROOT/pages/includes/attributes.adoc, docs/pom.xml, integration-tests/pom.xml, pom.xml, samples/exposedapp/pom.xml, samples/joke/pom.xml, samples/mysql-schema/pom.xml, samples/pingpong/pom.xml, samples/pom.xml
- chore: update version to 6.3.0-SNAPSHOT
- chore: prepare for 6.3.0 release
=> chore: release 6.3.0

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
=> chore: upgrade to Quarkus 3.2.6

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
This will be useful for a future upgrade of the Fabric8 Kubernetes
client.
=> refactor: leverage type inference more

pom.xml
=> chore: update to JOSDK 4.4.4

bundle-generator/runtime/src/main/resources/META-INF/quarkus-extension.yaml, core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
=> feat: add short-name for extensions, fix metadata

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleGenerator.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/Utils.java
=> feat: use package name in olm bundle's metadata

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleGenerator.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/ThirdReconciler.java, common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ConfigurationUtils.java
=> feat: add env var interpolating namespaces from OLM in CSV manifests

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/FirstReconciler.java, bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/BundleGenerationConfiguration.java, bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/CSVMetadataHolder.java
=> feat: enable setting version/replaces field from properties

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.3.3

.github/workflows/release.yml
=> fix: adjust for changed package

.github/project.yml, .github/workflows/build.yml, docs/modules/ROOT/pages/includes/attributes.adoc, docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, pom.xml
=> chore: update Quarkus to 3.2.8

README.md, build-parent/pom.xml, pom.xml
=> fix: remove repository definitions from POMs

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.3.4

pom.xml
=> chore: stay on Quarkus 3.5.2

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuildStep.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/DependentResourceSpecMetadata.java, pom.xml
=> feat: update to JOSDK 4.6.0

.github/workflows/release.yml
=> feat: also update Quarkus version in java-operators-plugin PR

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
- chore: update to Quarkus 3.6.0.CR1
- chore: release 6.5.0.Beta1
=> chore: update to Quarkus 3.6.0.CR1

.github/project.yml, .github/workflows/release.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> fix: syntax to extract Quarkus version

.github/workflows/build.yml, .github/workflows/quarkus-snapshot.yaml, .github/workflows/release.yml, .github/workflows/snapshot-release.yml, build-parent/pom.xml
=> feat: move to Java 17 minimum

.github/project.yml, .github/workflows/build.yml, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
=> fix: stay on Quarkus < 3.5 for 6.4 as we need to stay with Fabric8 6.7.2

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuildStep.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/CustomRateLimiterReconciler.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/NullItemStore.java, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
=> fix: allow configuration of field manager / item store

.github/workflows/build.yml
=> chore: update CI

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.5.0

.github/workflows/build-with-specific-quarkus-pr.yml
=> feat: add manual workflow to build against specific Quarkus PR

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.5.1

common/src/main/java/io/quarkiverse/operatorsdk/common/CLIConstants.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/devui/commands/APICommand.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/devui/commands/VersionsCommand.java, docs/modules/ROOT/pages/index.adoc
- docs(cli): improve descriptions and output of CLI commands
- docs(cli): add help option to api command
- docs: add information on CLI / Dev mode commands
=> feat: improve cli tools and docs

.github/workflows/build-for-quarkus-version.yml, .github/workflows/nightly-build-with-f8-snapshot.yml, .github/workflows/snapshot-release.yml, pom.xml
=> feat(ci): add profile to use snapshots, pass profiles to build

pom.xml
=> chore(deps): update to JOSDK 4.7.0

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.6.1

docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, pom.xml
=> chore(deps): update Quarkus to 3.7.1 & JOSDK to 4.8.0

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.6.2

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
Fixes #824
Previously, we were only registering the class itself for reflection, we
now register the full hierarchy instead.
=> fix: workaround quarkusio/quarkus#38657, register full hierarchies

docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, pom.xml
=> chore(deps): update Quarkus to 3.7.2

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/KubernetesLabelConfigOverrider.java, bundle-generator/deployment/src/main/resources/META-INF/services/io.smallrye.config.SmallRyeConfigBuilderCustomizer, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/OutputLabelSelectorsIfRequestedTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/Utils.java
=> feat: do not output kube version label in selector

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
=> chore: update to Quarkus 3.2.10

pom.xml
- **fix: remove unneeded variable to skip tests**
=> fix: remove unneeded variable to skip tests

bom/pom.xml, integration-tests/pom.xml, pom.xml, samples/pom.xml
- **chore(deps): update to Quarkus 3.7.4**
=> chore(deps): update to Quarkus 3.7.4

.github/project.yml, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/includes/attributes.adoc, docs/modules/ROOT/pages/index.adoc
=> chore: release 6.6.4

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/Version.java
=> fix: proper date parsing after update to git-commit-id 8.0.0

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.6.5

common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/DeserializedKubernetesResourcesBuildItem.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartDisabledLogger.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java
- **fix: properly log when helm generation is disabled**
- **fix: do not modify deployment as it is live and reused elsewhere**
=> fix: remove duplicated and wrong env variable

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
- **chore: update to JOSDK 4.8.2**
- **chore: release 6.6.7**
=> chore: update to JOSDK 4.8.2

README.md, bundle-generator/runtime/src/main/resources/META-INF/quarkus-extension.yaml, core/runtime/src/main/resources/META-INF/quarkus-extension.yaml, docs/modules/ROOT/pages/index.adoc
=> docs: added more information on getting started and how to use commands

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
=> chore: release 6.6.8

annotations/pom.xml, bom/pom.xml, build-parent/pom.xml, bundle-generator/deployment/pom.xml, bundle-generator/pom.xml, bundle-generator/runtime/pom.xml, cli/pom.xml, common-deployment/pom.xml, common/pom.xml, core/deployment/pom.xml, core/pom.xml, core/runtime/pom.xml, docs/pom.xml, integration-tests/pom.xml, pom.xml, samples/exposedapp/pom.xml, samples/joke/pom.xml, samples/mysql-schema/pom.xml, samples/pingpong/pom.xml, samples/pom.xml
- **chore: update to version 6.7.0-SNAPSHOT**
- **chore: update to Quarkus 3.9.4**
=> chore: update to Quarkus 3.10.0

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.7.0

pom.xml
=> chore(deps): update to Quarkus 3.11.0

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.7.1

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeControllerConfiguration.java, docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/SecretReconciler.java, integration-tests/src/main/resources/application.properties, integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
=> feat: configure max reconciliation interval via property

pom.xml
=> chore(deps): update Quarkus to 3.11.3

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/VersionAlignmentCheckingStep.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/Version.java, docs/modules/ROOT/pages/deploy-with-olm.adoc, samples/joke/README.md, samples/joke/src/main/java/io/quarkiverse/operatorsdk/samples/joke/JokeRequestReconciler.java, samples/joke/src/main/resources/application.properties, samples/pingpong/src/main/java/io/quarkiverse/operatorsdk/samples/pingpong/PingPongOperatorCSVMetadata.java, samples/pingpong/src/main/java/io/quarkiverse/operatorsdk/samples/pingpong/PingReconciler.java, samples/pingpong/src/main/java/io/quarkiverse/operatorsdk/samples/pingpong/PongReconciler.java, samples/pingpong/src/main/resources/application.properties
- **feat: add output of QOSDK and JOSDK version during build**
- **fix: remove use of deprecated package-name property**
=> fix: remove use of deprecated package-name property

.github/dependabot.yml
=> chore: monitor actions updates

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.7.2

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
=> chore(deps): upgrade to Quarkus 3.13.2

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/VersionAlignmentCheckingStep.java
=> feat: also output Fabric8 client versions

.github/scripts/installOperatorUsingOlm.sh, .github/workflows/build-for-quarkus-version.yml, .github/workflows/build.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release-quarkus-platform-pr.yml, .github/workflows/release-snapshot.yml, .github/workflows/release-update-java-operator-plugins.yml, .github/workflows/release.yml, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
=> feat: add maven wrapper support

pom.xml
=> chore(deps): update to Quarkus 3.14.0

pom.xml
=> chore(deps): update to JOSDK 4.9.3

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/BuildTimeConfigurationServiceBuildItem.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/BuildTimeConfigurationServiceBuildStep.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuildStep.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeConfigurationService.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java
- **feat: add build-time ConfigurationService implementation**
- **fix: only add PATCH verb if resource is creatable**
=> fix: add ConfigurationService implementation to support build-time resolution

.github/workflows/build-for-quarkus-version.yml
=> chore: update KinD

bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/ThirdReconciler.java, bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/BundleConfiguration.java, bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/BundleGenerationConfiguration.java, bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/CSVMetadataHolder.java
=> feat: provide per-bundle configuration via properties

.github/workflows/build-for-quarkus-version.yml, .github/workflows/release-snapshot-nightly-next-fabric8-version.yml, bom/pom.xml, pom.xml
=> feat: build using an arbitrary Fabric8 version without code changes

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
=> chore: release 6.8.0

.github/workflows/build-for-quarkus-version.yml, .github/workflows/release-snapshot-nightly-next-fabric8-version.yml
=> fix: remove broken snapshot release, use proper inputs

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.8.2

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.8.3

docs/modules/ROOT/pages/includes/quarkus-operator-sdk-bundle-generator.adoc, docs/modules/ROOT/pages/includes/quarkus-operator-sdk-bundle-generator_quarkus.operator-sdk.adoc, docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, docs/modules/ROOT/pages/includes/quarkus-operator-sdk_quarkus.operator-sdk.adoc
@metacosm I'm not sure if this is only on my PC, but these 4 files change with every build so I would like to add them to git.
=> chore: align generated docs file in git

.github/workflows/release-update-quarkus-platform.yml, bundle-generator/deployment/pom.xml
=> refactor: remove unneeded dependency

pom.xml
=> chore: remove unneeded properties that got added back by mistake

.github/project.yml, annotations/pom.xml, bom/pom.xml, build-parent/pom.xml, bundle-generator/deployment/pom.xml, bundle-generator/pom.xml, bundle-generator/runtime/pom.xml, cli/pom.xml, common-deployment/pom.xml, common/pom.xml, core/deployment/pom.xml, core/pom.xml, core/runtime/pom.xml, docs/modules/ROOT/pages/includes/attributes.adoc, docs/pom.xml, integration-tests/pom.xml, pom.xml, samples/exposedapp/pom.xml, samples/joke/pom.xml, samples/mysql-schema/pom.xml, samples/pingpong/pom.xml, samples/pom.xml
- **chore: update to 6.9.0-SNAPSHOT**
- **chore(deps): update to JOSDK 4.9.7**
- **chore: release 6.9.0**
=> chore: release 6.9.0

.github/project.yml, core/deployment/pom.xml, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGenerator.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneratorV1.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneratorV2.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDConfiguration.java, docs/modules/ROOT/pages/includes/attributes.adoc
Note that this should only be used if a blocking issue is found with the
v2 generator because the v1 version won't be supported moving forward.
=> feat: make it possible to revert to using the v1 CRD generator

core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDConfiguration.java
=> fix: sentence is now correct and makes sense (!)

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 6.9.2

samples/exposedapp/src/main/resources/application.properties, samples/joke/src/main/resources/application.properties, samples/mysql-schema/src/main/resources/application.properties, samples/pingpong/src/main/resources/application.properties
=> chore: remove now unneeded workaround

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
- **chore(deps): update to Quarkus 3.18.0.CR1**
- **chore: release 7.0.0.CR1**
=> chore: release 7.0.0.CR1

pom.xml
=> chore: update to Quarkus 3.17.8

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 7.0.0

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc, pom.xml
- **chore: update to JOSDK 5.0.1**
- **chore: release 7.0.1**
=> chore: update to JOSDK 5.0.1

pom.xml
=> chore: update to JOSDK 5.0.2

pom.xml
=> chore: update to Quarkus 3.19.0

annotations/pom.xml, bom/pom.xml, build-parent/pom.xml, bundle-generator/deployment/pom.xml, bundle-generator/pom.xml, bundle-generator/runtime/pom.xml, cli/pom.xml, common-deployment/pom.xml, common/pom.xml, core/deployment/pom.xml, core/pom.xml, core/runtime/pom.xml, docs/pom.xml, integration-tests/pom.xml, pom.xml, samples/exposedapp/pom.xml, samples/joke/pom.xml, samples/mysql-schema/pom.xml, samples/pingpong/pom.xml, samples/pom.xml
- **fix: only use plain kubernetes client minimally**
- **chore: change version to 7.1.0-SNAPSHOT**
=> fix/feat: only use plain kubernetes client minimally

core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/InjectedDependency.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/NoDefaultArgConstructorDependent.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/TestReconciler.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeConfigurationService.java
=> fix: BuildTimeConfigurationService should resolve DR types directly

.github/project.yml, docs/modules/ROOT/pages/includes/attributes.adoc
=> chore: release 7.1.1

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGenerationBuildStep.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/AppEventListener.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDInfo.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDInfos.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDUtils.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java, integration-tests/pom.xml, samples/external-crd/external-crds/external.crd.yml, samples/external-crd/pom.xml, samples/external-crd/src/main/java/io/quarkiverse/operatorsdk/ExternalCRDReconciler.java, samples/external-crd/src/main/resources/application.properties, samples/external-crd/src/test/java/io/quarkiverse/operatorsdk/it/ExternalCRDTest.java, samples/pom.xml
- **refactor: use CRD spec version from the info**
- **feat: apply external CRDs during test / dev mode**
=> feat: apply external CRDs during test / dev mode

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/HelmConfiguration.java, docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, docs/modules/ROOT/pages/includes/quarkus-operator-sdk_quarkus.operator-sdk.adoc
=> feat: configure Helm chart name with quarkus.operator-sdk.helm.name

annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/CSVMetadata.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java, bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java, bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/ThirdReconciler.java, bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/CSVMetadataHolder.java
If accepted, should be ported to main for #1088.
=> fix: Allow to add labels in CSVMetadata

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneratorV1.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneratorV2.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/ExcludedCRDGenerationTest.java, core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/LabelAdderCRDPostProcessor.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDConfiguration.java, docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc, docs/modules/ROOT/pages/includes/quarkus-operator-sdk_quarkus.operator-sdk.adoc
=> feat: make it possible to configure a CRDPostProcessor

core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneratorV1.java, core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneratorV2.java, core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusBuildTimeControllerConfiguration.java
See https://github.com/quarkusio/quarkus/pull/48432
=> fix: remove use of Quarkus Log which shouldn't be used in extensions

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/deploy-with-kubernetes-deployment.adoc
=> docs: Add docs for deploying operator using a Kubernetes deployment

samples/exposedapp/src/test/java/io/halkyon/HelmDeploymentE2EIT.java
=> fix: ensure test resource is deleted before the end of each Helm test
