- deployment/pom.xml
- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- pom.xml
- runtime/pom.xml
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ExternalConfiguration.java
The output location is configurable using the
`quarkus.operator-sdk.crd-output-directory` property with a path
relative to the output directory of your application.
Currently relies on snapshot version of soon to be released fabric8 kubernetes-client 5.2.
Fixes #5.
> feat: extension now generates CRDs instead of apt

- integration-tests/pom.xml
- pom.xml
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java
Note that the fix relies on a heuristics so it might not always work.
Unfortunately, there is no standard way to retrieve the "original" class
name after it's been proxied / wrapped several times by different
extensions in different ways… 😭 
Fixes #16
> fix: extract proper controller name from wrapped classes

- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java
Hello,
This pull request will initialize the Operator using the default Quarkus ObjectMapper allowing additional modules to be registered (e.g. java.time support).
Please let me know of any feedback you may have.
> use the default quarkus object mapper when initializing the operator.

- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java
The issue was that, in some conditions, the Controller annotation would
get lost and the controller name couldn't be properly resolved. To
bypass this issue, we now record which name is associated to which
controller class when a controller is registered.
Fixes #47
> fix: use class name to retrieve controller name

- .github/workflows/release.yml
> Indicate the branch when pushing the tags

- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/ConfigurationServiceBuildItem.java
- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDConfiguration.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDGenerationInfo.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java
- samples/src/main/resources/application.properties
This only partially addresses the UX of applying CRDs when missing as it only deals with the case where the CRD is missing during the controller's registration.
> Make the extension able to automatically apply CRDs when not present on the cluster

- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/BuildTimeHybridControllerConfiguration.java
- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java
- integration-tests/src/main/resources/application.properties
- integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeOperatorConfiguration.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeOperatorConfiguration.java
Properties at the `quarkus.operator-sdk` level can set defaults for
similarly named controller-specific properties, which will take effect
for all controllers that do not specifically override the value.
Fixes #74
> feat: make it possible to set default values for all controllers

- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/ContextStoredCRDInfos.java
- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java
- integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
- pom.xml
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDGenerationInfo.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDInfo.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java
This behavior is controlled by the `quarkus.operator-sdk.crd.apply` property. When set to `true`, any change impacting the CRD will trigger a regeneration and apply the new CRD to the cluster automatically.
Fixes #11 
Fixes #12
> Apply CRD when changes happened during dev that impact them

- deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/AppEventListener.java
> feat: add automatic closure of operator on shut down

- samples/src/main/java/io/quarkiverse/operatorsdk/samples/joke/JokeController.java
- samples/src/main/java/io/quarkiverse/operatorsdk/samples/joke/JokeService.java
fixes #143 
Use a @QueryParam for the type to avoid double "?" and "%3F" in URI:
previously was:
```
2021-11-05 16:14:45,396 DEBUG [org.apa.htt.imp.exe.MainClientExec] (EventHandler-jokecontroller) Executing request GET /joke/Any/any%3Ftype=single?blacklistFlags=nsfw%2Cracist%2Csexist&safe-mode=false HTTP/1.1
``` 
now:
```
DEBUG [org.apa.htt.wire] (EventHandler-jokecontroller) http-outgoing-0 >> "GET /joke/Any/any?blacklistFlags=nsfw%2Cracist%2Csexist&safe-mode=false&type=single HTTP/1.1[\r][\n]"
```
> fix: query param remove double "?" generation

- csv-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/csv/deployment/CSVGenerator.java
- csv-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/csv/deployment/CSVProcessor.java
- samples/pom.xml
- samples/src/main/resources/application.properties
> test: exhibit build cycle

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddRoleBindingsDecorator.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/BuildTimeHybridControllerConfiguration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CustomResourceControllerMapping.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeControllerConfiguration.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeOperatorConfiguration.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java
Fixes #154 and java-operator-sdk/java-operator-sdk#699.
Ping @lburgazzoli @poikilotherm: would be great if you could give this PR a try and let me know if this addresses your issues. If yes, I'll cut a release.
> Fix RBAC generation issues

- .github/workflows/build.yml
This will allow to discover errors like https://github.com/quarkiverse/quarkus-operator-sdk/issues/175
I pushed first without the update to 2.6.1 that fix the VersionInfo serialization error. Build should failed.
> Run it tests in native mode

- pom.xml
Fixes #224, at least partially. More complete fix would probably need to
disable building the `integration-tests` module altogether to avoid
Quarkus building the test reconcilers.
> feat: initial support for -Dquickly

- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/AppEventListener.java
> fix: do not start operator if no controller is registered

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/AppEventListener.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeOperatorConfiguration.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java
The configuration option is `quarkus.operator-sdk.start-operator=false`.
Fixes #207
> feat: make it possible to not automatically start the operator

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleGenerator.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/AnnotationsManifestsBuilder.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/BundleDockerfileManifestsBuilder.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/ManifestsBuilder.java
- bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/CSVMetadata.java
- samples/mysql-schema/pom.xml
- refactor: use java.util.Set operation instead of Sets from Arc
- refactor: use String.join instead of stream operations
- refactor: rename getYAMLData to more appropriate getManifestData
- refactor: remove unneeded field
- refactor: use append instead of concatenation
- fix: remove unused warnings
- fix: wrong field was used
- refactor: minor improvements
- refactor: remove dependency on commons-lang3 Fixes #257
- fix: logging
> improvements

- bom/pom.xml
The goal here is to make the snapshot version available to test with quarkus extension
> fix: use josdk 2.1.2-SNAPSHOT

- .github/scripts/installOperatorUsingOlm.sh
- .github/scripts/testPingPongSample.sh
- .github/workflows/build.yml
- bundle-generator/deployment/pom.xml
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleGenerator.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CustomResourceManifestsBuilder.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/DefaultBundleWhenNoCsvMetadataTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/First.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/FirstReconciler.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/ReconcilerWithNoCsvMetadata.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/Second.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/SecondReconciler.java
- samples/joke/README.md
- fix: allow to generate multiple operators from different reconcilers
- adding test to bundle extension to cover when csvmetadata is not used
- chore: check that all the files are indeed generated
- fix: proper file name for generated CRDs
> fix bundle generator

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/deployment/CRDGenerationTest.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDConfiguration.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDGenerationInfo.java
- integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
It is now impossible to automatically apply the CRD to the cluster in
normal mode, even if explicitly asked for, to prevent potential issues
in production. CRD is automatically applies in dev or test mode now,
though, which is different from the previous behavior, where you needed
to activate the feature explicitly.
Fixes #297
> feat!: explicit interaction between CRD generate/apply and launch mode

- .github/project.yml
- bom/pom.xml
- build-parent/pom.xml
- integration-tests/pom.xml
- pom.xml
- samples/joke/pom.xml
- samples/mysql-schema/pom.xml
- feat: also release snapshots for 3.0.x branch
- chore: update to JOSDK 2.1.4-SNAPSHOT
- feat: use mariadb as drop-in mysql replacement
- fix: remove version override
- chore: update to Fabric8 client 5.12.2
- chore: update to JOSDK 2.1.4
- fix: also add finalizers to target resources in roles when needed
- chore: release 3.0.7
- fix: shouldn't start operator when testing
- fix: disable delayed registration test
- fix: always add finalizers sub-resource since it's widely used
- [maven-release-plugin] prepare release 3.0.7
- [maven-release-plugin] prepare for next development iteration
- chore: improve build and upgrade to Quarkus 2.7.6
- chore: prepare for 3.0.8 release
> release 3.0.8

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java
@metacosm Quarkus 2.7, which is the latest productized version, brings an older version of Jandex. This PR makes the project compatible with Quarkus 2.7 at the expense of using a deprecated method (until a new productized version of Quarkus is released).
Maybe setting up a CI that overrides the Quarkus version and checks the compatibility would prevent similar issues in the future?
> fix: keep the project compatible with Quarkus 2.7

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/KubernetesClientSerializationCustomizer.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusConfigurationService.java
- docs/modules/ROOT/pages/index.adoc
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/EmptyCR.java
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/EmptyReconciler.java
- integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
- feat: make it possible to customize Fabric8's mapper
- fix: register CDI qualifier so that beans can properly be found
- docs: add bit about fabric8's serialization customization
> feat: allow customization of Fabric8's ObjectMapper

- bom/pom.xml
- pom.xml
Removes the version override for `io.fabric8:kubernetes-*`. Versions of these dependencies are already contained in the `quarkus-bom`.
@metacosm This removes the version override we discussed.
> fix: remove fabric8 k8s client version override

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
All operators in Kubernetes and Openshift Community Operators repositories uses `.clusterserviceversion.yaml` for filename. 
I would like to propose to sync ClusterServiceVersion filename generated by quarkus-operator-sdk with operators repository.
> Sync clusterserviceversion filename and extension

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- samples/pingpong/src/test/java/io/quarkiverse/operatorsdk/samples/pingpong/AssertGeneratedResourcesIT.java
Before these changes, the permissions were duplicated for clusterPermissions and permissions in the CSV manifests:
```yaml
clusterPermissions:
- rules:
- apiGroups:
- apiextensions.k8s.io
resources:
- customresourcedefinitions
verbs:
- get
- list
serviceAccountName: quarkus-operator-sdk-samples-pingpong
- rules:
- apiGroups:
- apiextensions.k8s.io
resources:
- customresourcedefinitions
verbs:
- get
- list
serviceAccountName: quarkus-operator-sdk-samples-pingpong
```
And should have only one:
```yaml
clusterPermissions:
- rules:
- apiGroups:
- apiextensions.k8s.io
resources:
- customresourcedefinitions
verbs:
- get
- list
serviceAccountName: quarkus-operator-sdk-samples-pingpong
```
Moreover, the new logic will aggregate the rules onto the permission with the same service account name.
> Fix having duplicate permissions in generated CSV

- .github/workflows/build-for-quarkus-version.yml
- .github/workflows/build.yml
- chore: remove deprecated set-output usage
- chore: update kind-action to v2 to avoid nodejs 12 deprecation
> chore: update actions to handle deprecation warnings

- .github/project.yml
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
- pom.xml
- fix: make CRD order predictable in CSV
- chore: release 4.0.8
> fix: make CRD order predictable in CSV

- .github/project.yml
- .github/workflows/build.yml
- pom.xml
- chore: deactivate snapshots
- chore: use Quarkus 3.0.0.CR1 to build against
- chore: release 6.0.0.CR1
> release 6.0.0.CR1

- .github/project.yml
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeOperatorConfiguration.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
- fix: default to only emit warning on version misalignment
- chore: release 6.0.1
> fix: default to only emit warning on version misalignment

- .github/workflows/build-for-quarkus-version.yml
- docs/pom.xml
- samples/exposedapp/src/main/resources/application.properties
- samples/joke/src/main/resources/application.properties
- samples/mysql-schema/src/main/resources/application.properties
- samples/pingpong/src/main/resources/application.properties
- fix: remove unneeded Quarkus plugin
- refactor: make it possible to run the tests in parallel
- refactor: only natively build tests and samples, in parallel
> feat: natively build samples in parallel

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleReconcilerWithSharedMetadataBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleReconcilerWithSharedMetadataGroupBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleReconcilerWithoutSharedMetadataBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/Utils.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/AReconciler.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/BReconciler.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/CReconciler.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/DuplicatedBundleNameWithoutSharedCSVMetadata1.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/DuplicatedBundleNameWithoutSharedCSVMetadata2.java
- bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/CSVMetadataHolder.java
- feat: log bundle assignment for each reconciler
- feat: fail when reconcilers use the same bundle without shared metadata
> feat: improve handling & reporting around shared CSV metadata

- core/deployment/pom.xml
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java
The reason it was previously failing is that
Dekorate could not find a valid Maven project
in the temp directory in which QuarkusProdModeTest bootstraps the Quarkus application.
In order to make it work, we need to ensure that
the aforementioned temp directory is created under the project root, so Dekorate then finds it by moving up the file system.
The same thing is done in the Quarkus repo to
make the Kubernetes related QuarkusProdModeTest
tests work.
The reason argLine is used instead of systemProperties is mentioned in the comment
> Enable OperatorSDKTest

- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ConfigurationUtils.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/Constants.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AnnotationConfigurablesBuildItem.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGenerationBuildStep.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QOSDKReflectiveClassBuildItem.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuildStep.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuilder.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/ReconcilerInfosBuildItem.java
Separate the configuration and CRD generation steps in the
deployment process and introduce new build items to support it.
Now reconcilers, annotation configurables, classes for reflection,
and dependent beans are managed in separate steps. This refactoring
improves maintainability and simplifies the Operator SDK Processor.
- refactor: lazily initialize CRD generator
- refactor: extract configuration creation logic
- refactor: remove unneeded constants
- refactor: extract changed classes extraction logic
- refactor: move application handling to own step
- refactor: split configuration & CRD generation steps
> refactor: split configuration & CRD generation steps

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGenerationBuildStep.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/NoCRDGenerationTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java
The item wasn't previously created if CRD generation was disabled, which
prevented the build to proceed normally.
> fix: ensure that GeneratedCRDInfoBuildItem is always available

- docs/modules/ROOT/pages/index.adoc
- docs: add link to blog series
- docs: move bundle generation out of preview
- docs: deprecate QOSDK's ObjectMapper customization mechanism
> docs: improve documentation

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/BuildTimeHybridControllerConfiguration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuildStep.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/BuildTimeControllerConfiguration.java
- docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
- integration-tests/src/main/resources/application.properties
The previous behavior precluded operator-level defaulting at runtime
because setting the `generate-with-watched-namespaces` property was
marking the controller as having explicitly set namespaces. We now only
set that status if and only if namespaces were set using annotations.
Fixes #653
> fix: runtime namespaces should always override buildtime values

- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDUtils.java
> Fix CRDUtils::apply by replacing serverSideApply() with get(), update() and create()

- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/Constants.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeOperatorConfiguration.java
- docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
This makes the empty string in the namespaces configuration watch all namespaces, as per the documented behaviour: https://github.com/quarkiverse/quarkus-operator-sdk/blob/main/core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeOperatorConfiguration.java#L56
Fixes #656
> Treat empty runtime namespaces as All Namespaces mode

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGenerationBuildStep.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/AllCRDGenerationTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/ExcludedCRDGenerationTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/External.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDConfiguration.java
- docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
A new configuration property quarkus.operator-sdk.crd.exclude-resources
has been introduced to provide fully-qualified class names of resource
classes to be excluded from CRD generation.
Fixes #674
> feat: allow for exclusion of some classes when generating CRDs

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/Utils.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/FirstReconciler.java
- bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/CSVMetadataHolder.java
> feat: provide a CSV.spec.version value when possible

- bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/BundleGenerationConfiguration.java
> fix: bundle generation configuration shouldn't be available at runtime

- annotations/pom.xml
- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/AdditionalRBACRules.java
- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/RBACRule.java
- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/RBACVerbs.java
- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/Verbs.java
- bom/pom.xml
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- common-deployment/pom.xml
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/Constants.java
- common/pom.xml
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuildStep.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/SimpleReconciler.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/TestReconciler.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/QuarkusControllerConfiguration.java
- pom.xml
- chore: remove unneeded dependency
- feat: add annotations module with RBAC-related annotations
- refactor: move verb constants to new Verbs class in annotations module
- refactor: rename constants more appropriately, add more
- refactor: rename Verbs to more precise RBACVerbs
- feat: make RBACRule repeatable, add ALL constant
- feat: support adding extra RBAC rules via annotations
> feat: support adding extra RBAC rules via annotations

- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/CSVMetadata.java
- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/SharedCSVMetadata.java
- bundle-generator/deployment/pom.xml
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/AReconciler.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/BReconciler.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/DuplicatedBundleNameWithoutSharedCSVMetadata1.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/DuplicatedBundleNameWithoutSharedCSVMetadata2.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/External.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/FirstReconciler.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/SecondReconciler.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/Third.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/ThirdReconciler.java
- bundle-generator/runtime/pom.xml
- bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/SharedCSVMetadata.java
- samples/joke/pom.xml
- samples/joke/src/main/java/io/quarkiverse/operatorsdk/samples/joke/JokeRequestReconciler.java
- samples/pingpong/src/main/java/io/quarkiverse/operatorsdk/samples/pingpong/PingPongOperatorCSVMetadata.java
> refactor: move CSV-related annotation & interface to annotations module

- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeControllerConfiguration.java
- docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
Fixes #725
@metacosm  If there are soem tests which I can draw inspiration from, let me know and I will add some coverage. Otherwise I will be leaving this up to you as understanding how exactly I should write the tests is something I don't have the time for right now.
> fix: runtime namespaces are now correctly set from controller properties 

- bundle-generator/deployment/pom.xml
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
This pull request addresses: https://github.com/quarkusio/quarkus/issues/36041
So, what's the issue?
dekorate and by extension quarkus-kubernetes need to run from within an actual project (gradle, maven etc). 
This is not the case in prod mode tests as the contain no sources and no build files.
In quarkus we workaround the issue by generating temp directories under an actual project dir.
Let's do the same here.
> Fix bundle-generator/deployment manifest generation in integration tests

- cli/pom.xml
- cli/src/main/java/io/quarkiverse/operatorsdk/cli/API.java
- cli/src/main/java/io/quarkiverse/operatorsdk/cli/QOSDKCommand.java
- cli/src/main/resources/application.properties
- common/pom.xml
- common/src/main/java/io/quarkiverse/operatorsdk/common/CLIConstants.java
- common/src/main/java/io/quarkiverse/operatorsdk/common/Files.java
- common/src/main/resources/templates/cli/api/reconciler.qute
- common/src/main/resources/templates/cli/api/resource.qute
- common/src/main/resources/templates/cli/api/spec.qute
- common/src/main/resources/templates/cli/api/status.qute
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/devui/commands/APICommand.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/devui/commands/ConsoleCommands.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/devui/commands/VersionsCommand.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/Version.java
- core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
- pom.xml
- chore: initial work on CLI plugin
- wip: first commands layout
- feat: first implementation of API creation command
> feat: add Quarkus CLI commands

- .github/project.yml
- .github/workflows/build.yml
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- docs/modules/ROOT/pages/includes/attributes.adoc
- integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
- pom.xml
> chore: update to Quarkus 3.5.0

- .github/workflows/release.yml
More concretely do everything pertaining to quarkus-platform (including
PR creation) before starting the update of OSDK plugins PR process. This
way, if one step fails, the other one can still go through, since they
are independent.
[skip ci]
> refactor: do related steps in succession instead of by "type"

- .github/workflows/release.yml
- refactor: do related steps in succession instead of by "type"
- fix: checkout 3.2 branch of platform project
- fix: do not update OSDK plugin when releasing 6.3
> fix: adapt release process for 6.3.x maintenance branch

- .github/project.yml
- core/runtime/pom.xml
- docs/modules/ROOT/pages/includes/attributes.adoc
This is needed so that the cli-plugins field in quarkus-extension.yml is
properly populated.
> fix: enable resource filtering

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/QuarkusControllerConfigurationBuildStep.java
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/ConfiguredReconciler.java
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/CustomRateConfiguration.java
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/CustomRateLimiter.java
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/CustomRateLimiterReconciler.java
- integration-tests/src/main/java/io/quarkiverse/operatorsdk/it/OperatorSDKResource.java
- integration-tests/src/test/java/io/quarkiverse/operatorsdk/it/OperatorSDKResourceTest.java
> fix: make DefaultRateLimiter class discoverable for configuration

- .github/workflows/build.yml
> fix: run CI on Quarkus 3.6.0 now that it's released

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/FailOnDeprecatedAnnotationsTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/DeprecatedReconciler.java
Supporting both deprecated and replacement versions is too complex for
a corner use case to support, so we now fail the build when users are
still using the deprecated version to inform them instead of failing
silently.
Fixes #770
> feat: fail build if using deprecated CSV features

- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/RunTimeControllerConfiguration.java
- docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
> fix: runtime namespaces are now correctly set from controller properties (#726)

- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/AppEventListener.java
During troublesheeting an issue the QOSDK was shutting down unexpectedly, this will give more information if it comes from OS or the app exists.
> feat: log if shutdown was standard or not

- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/CSVMetadata.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/SecondReconciler.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java
- samples/joke/src/main/java/io/quarkiverse/operatorsdk/samples/joke/JokeRequestReconciler.java
- fix: use Kubernetes configuration for name and version when available
- refactor: RBACRule should be used instead of PermissionRule
> fix: use Kubernetes configuration for name and version when available

- .github/project.yml
- annotations/pom.xml
- bom/pom.xml
- build-parent/pom.xml
- bundle-generator/deployment/pom.xml
- bundle-generator/pom.xml
- bundle-generator/runtime/pom.xml
- cli/pom.xml
- common-deployment/pom.xml
- common/pom.xml
- core/deployment/pom.xml
- core/pom.xml
- core/runtime/pom.xml
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/pom.xml
- integration-tests/pom.xml
- pom.xml
- samples/exposedapp/pom.xml
- samples/joke/pom.xml
- samples/mysql-schema/pom.xml
- samples/pingpong/pom.xml
- samples/pom.xml
- chore: update version to 6.6.0-SNAPSHOT
- feat: move to Java 17 baseline
- chore: release 6.6.0
> feat: move to Java 17 baseline, release 6.6.0

- .github/workflows/build-for-quarkus-version.yml
- .github/workflows/codeql-analysis.yml
> fix(ci): do not use CodeQL autobuild, build quickly with snapshots

- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/FileUtils.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/GeneratedResourcesUtils.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/HelmChartWatchAllNamespacesGeneratorTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/WatchAllNamespacesReconciler.java
When a reconciler is configured to watch all namespaces, a ClusterRoleBinding object is generated by
AddRoleBindingsDecorator, and it later gets appended to templates/kubernetes.yml by HelmChartProcessor.
However, that file becomes syntactically invalid because FileUtils.asYaml produces a top-level YAML array when passed a List. That's not what Helm expects.
When one tries to install the generated chart, the following error is returned:
Error: INSTALLATION FAILED: YAML parse error on
[...]/templates/kubernetes.yml: error unmarshaling JSON:
while decoding JSON: json: cannot unmarshal array into
Go value of type releaseutil.SimpleHead
YAML parse error on [...]/templates/kubernetes.yml
> fix: helm chart generates invalid YAML when watching all namespaces

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/Values.java
- core/deployment/src/main/resources/helm/crd-role-binding-template.yaml
- core/deployment/src/main/resources/helm/static/README.md
- core/deployment/src/main/resources/helm/static/generic-crd-cluster-role-binding.yaml
- core/deployment/src/main/resources/helm/static/generic-crd-cluster-role.yaml
- core/deployment/src/main/resources/helm/static/service.yaml
- core/deployment/src/main/resources/helm/static/serviceaccount.yaml
- core/deployment/src/main/resources/helm/static/values.schema.json
drops redundant `Values.version`
> improve: use chart appVersion in labels

- .github/project.yml
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/index.adoc
> chore: release 6.6.3

- .github/scripts/testJokeSample.sh
- .github/workflows/build-for-quarkus-version.yml
- .github/workflows/build.yml
- samples/exposedapp/src/main/java/io/halkyon/ExposedAppReconciler.java
- **feat(ci): also test joke operator in native mode**
- **feat(ci): validate ExposedApp CSV**
- **fix(ci): revert to use latest operator-sdk version**
> feat(ci): improve operator testing

- .github/workflows/build-for-quarkus-version.yml
- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/CSVMetadata.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleGenerator.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/ManifestsBuilder.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/DefaultBundleWhenNoCsvMetadataTest.java
- bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/BundleGenerationConfiguration.java
- bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/CSVMetadataHolder.java
- samples/exposedapp/src/main/java/io/halkyon/ExposedAppReconciler.java
- **feat: automatically add provider name and URL based on user and git repo**
- **feat(ci): validate all bundles except Joke that OLM v1 doesn't like**
- **feat: split name into bundle and csv names to avoid confusion**
- **fix: sanitize version**
> feat: improve OLM support

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleGenerator.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- bundle-generator/runtime/src/main/java/io/quarkiverse/operatorsdk/bundle/runtime/BundleGenerationConfiguration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java
> refactor: switch BundleGenerationConfiguration to ConfigMapping

- .github/workflows/build-for-quarkus-version.yml
@metacosm unfortunately, run_name didn't work as I expected - https://github.com/quarkiverse/quarkus-operator-sdk/actions/runs/10388877313, so I'm moving this into an output of the build step.
> fix: move input parameters into a build step

- core/deployment/pom.xml
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/ResourceControllerMapping.java
> feat: update to v2 version of Fabric8's CRD generator

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/ThirdReconciler.java
This PR removes duplicate entries from the generated CSV's `spec.nativeAPIs` array.
Currently, output like the following may occur when multiple dependent resources handle native k8s types of the same kind, such as [1].
```yaml
...
spec:
...
nativeAPIs:
- kind: ConfigMap
group: ""
version: v1
- kind: Secret
group: ""
version: v1
- kind: ServiceAccount
group: ""
version: v1
- kind: ServiceAccount
group: ""
version: v1
- kind: Service
group: ""
version: v1
- kind: Service
group: ""
version: v1
- kind: Deployment
group: apps
version: v1
- kind: Deployment
group: apps
version: v1
- kind: Ingress
group: networking.k8s.io
version: v1
- kind: ClusterRoleBinding
group: rbac.authorization.k8s.io
version: v1
- kind: ClusterRoleBinding
group: rbac.authorization.k8s.io
version: v1
- kind: ClusterRole …
```
> fix: Remove duplicate CSV nativeAPIs, sort by multi-field comparator

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/TestReconciler.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/TypelessAnotherKubeResource.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/TypelessKubeResource.java
Typeless kubernetes resource has no Group and Plural value, so generating wrong policy rule.
Commit summary:
1) Use ApiGroup value from GVK and '*' for Plural value if dependent resource is assignable from GenericKubernetesDependentResource 2) Merge verbs in rule for optimization if with same ApiGroups and Resources
> Support typeless kubernetes resources when generating manifests

- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/RBACVerbs.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ConfigurationUtils.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/TypelessAnotherKubeResource.java
- **refactor: merge rules as they are collected**
- **feat: throw an exception if class is not found in index**
- **fix: use plural form instead of wildcard, adapt tests**
> feat: improve RBAC generation for typeless dependents

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java
- pom.xml
> chore(deps): update JOSDK to 4.9.4

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
> fix: ignore vertx warning in reflective hierarchy during compilation

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
> fix: ignore okhttp3 jandex warnings for gradle builds

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddRoleBindingsDecorator.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/WatchAllNamespacesTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/WatchAllReconciler.java
An improper name was generated in case a controller watched all
namespaces.
Fixes #869
> fix: generate proper RoleRef name for ClusterRoleBindings

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java
> fix: warn when dependent cannot be instantiated for generic or SSA needs

- .github/workflows/build-for-quarkus-version.yml
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/AddClusterRolesDecorator.java
- samples/exposedapp/src/main/resources/application.properties
- samples/joke/src/main/resources/application.properties
- samples/mysql-schema/src/main/resources/application.properties
- samples/pingpong/src/main/resources/application.properties
- **refactor: simplify SSA check in RBAC generation**
- **fix: workaround for operator-framework/java-operator-sdk#2526**
- **chore: update to JOSDK 4.9.5**
> Improve RBAC generation using JOSDK 4.9.5 features

- .github/project.yml
- docs/modules/ROOT/pages/includes/attributes.adoc
- docs/modules/ROOT/pages/index.adoc
> chore: release 6.8.1

- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/AllCRDGenerationTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/OperatorSDKTest.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/External.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/ExternalV1.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/SimpleCRV2.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/SimpleReconcilerV2.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/sources/SimpleSpecV2.java
> chore(tests): add multiple versions CRs to CRD generation tests

- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/Constants.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/CustomResourceAugmentedClassInfo.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/DependentResourceAugmentedClassInfo.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ReconciledAugmentedClassInfo.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ReconciledResourceAugmentedClassInfo.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ReconcilerAugmentedClassInfo.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/ResourceAssociatedAugmentedClassInfo.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGenerationBuildStep.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/ResourceControllerMapping.java
- core/deployment/src/test/java/io/quarkiverse/operatorsdk/test/AllCRDGenerationTest.java
Also fixes an issue with improperly recorded reconciler name and
handling of generic kubernetes resources.
Fixes #886
> fix: record version with CRD name to properly output multiple versions

- core/deployment/pom.xml
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/VersionAlignmentCheckingStep.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/Version.java
> feat: add info endpoint contribution with version details

- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/BundleProcessor.java
- pom.xml
> chore(deps): update to Quarkus 3.17.0.CR1

- core/deployment/pom.xml
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneration.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGenerator.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneratorV1.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/CRDGeneratorV2.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDConfiguration.java
Note that this should only be used if a blocking issue is found with the
v2 generator because the v1 version won't be supported moving forward.
> feat: make it possible to revert to using the v1 CRD generator

- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/CRDConfiguration.java
- docs/modules/ROOT/pages/includes/quarkus-operator-sdk.adoc
- docs/modules/ROOT/pages/includes/quarkus-operator-sdk_quarkus.operator-sdk.adoc
- docs/modules/ROOT/pages/index.adoc
> doc: clarify that CRDs are never applied in prod mode

- pom.xml
- samples/exposedapp/src/main/resources/application.properties
- samples/joke/src/main/resources/application.properties
- samples/mysql-schema/src/main/resources/application.properties
- samples/pingpong/src/main/resources/application.properties
- **chore: remove now unneeded workaround**
- **chore(deps): update to Quarkus 3.15.2**
> chore: remove now unneeded workaround after Quarkus 3.15.2 update

- .github/project.yml
- .github/workflows/release-quarkus-platform-pr.yml
- .github/workflows/release-update-quarkus-platform.yml
> chore: move Quarkus platform PR info to the project.yml file

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/HelmChartProcessor.java
- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/helm/Values.java
With this a new property `image` is added to the `values.yaml` so that the users can override it if need. 
Tested with Debezium Operator.
```yaml
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
annotations:
app.quarkus.io/quarkus-version: "3.17.0"
labels:
app.kubernetes.io/name: "debezium-operator"
app.kubernetes.io/managed-by: "quarkus"
name: "debezium-operator"
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: "debezium-operator"
template:
metadata:
annotations:
app.quarkus.io/quarkus-version: "3.17.0"
labels:
app.kubernetes.io/managed-by: "quarkus"
app.kubernetes.io/name: "debezium-operator"
spec:
containers:
- env:
- name: "KUBERNETES_NAMESPACE"
valueFrom:
fieldRef:
fieldPath: "metadata.namespace"
- name: …
```
> feat: Add possibility to override deployment image

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/devui/DevUIProcessor.java
This is due to an upcoming change in Execution Model Validation [1] where we need the `JsonRPCProvidersBuildItem` produced always, not only in dev mode. JSON RPC providers can use execution model affecting annotations, so we need to know about them, otherwise a non-dev build would fail with an incorrect validation error.
[1] https://github.com/quarkusio/quarkus/pull/46965
> Dev UI: always produce JsonRPCProvidersBuildItem

- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/OperatorProducer.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/api/ConfigurableReconciler.java
If a reconciler implements `ConfigurableReconciler`, then QOSDK will
derive a new configuration for the reconciler by calling
`updateConfigurationFrom` before registering the reconciler with this
new configuration.
> feat: allow reconcilers to override their configuration at runtime

- samples/joke/pom.xml
- samples/joke/src/test/java/io/quarkiverse/operatorsdk/samples/joke/JokeRequestReconcilerTest.java
It seems that before https://github.com/quarkusio/quarkus/pull/48977 the `quarkus-test-kubernetes-client` was not correctly recognized and the Kubernetes Client Dev Services were able to start the container. But after this change the extension presence is correctly detected and thus the containers are not started.
> fix: remove test-kubernetes-client from the joke sample to use provided Dev Services

- core/deployment/src/main/java/io/quarkiverse/operatorsdk/deployment/OperatorSDKProcessor.java
- core/runtime/src/main/java/io/quarkiverse/operatorsdk/runtime/ConfigurationServiceRecorder.java
Fixes #1141 
I don't understand why that docs changes got there when I built the project. But they are staying there so I'm keeping them in this PR.
> fix: inject RunTimeOperatorConfiguration as RuntimeValue

- samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/MySQLSchemaReconciler.java
- samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/dependent/SchemaDependentResource.java
- samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/dependent/SecretDependentResource.java
- samples/mysql-schema/src/main/java/io/quarkiverse/operatorsdk/samples/mysqlschema/schema/Schema.java
- samples/mysql-schema/src/test/java/io/quarkiverse/operatorsdk/samples/mysqlschema/MySQLSchemaOperatorE2ETest.java
- **fix: override getSecondaryResource to properly get associated resource**
- **refactor: use constants instead of hardcoding values**
- **feat: fail if schema already exists in DB**
- **feat: add toString implementation**
- **feat: wait for secret before attempting to create the schema**
> fix: override getSecondaryResource to properly get associated resource

- annotations/src/main/java/io/quarkiverse/operatorsdk/annotations/CSVMetadata.java
- bundle-generator/deployment/src/main/java/io/quarkiverse/operatorsdk/bundle/deployment/builders/CsvManifestsBuilder.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/MultipleOperatorsBundleTest.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/OptionalExplicitNativeDependent.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/OptionalImplicitNativeDependent.java
- bundle-generator/deployment/src/test/java/io/quarkiverse/operatorsdk/bundle/sources/ThirdReconciler.java
- common-deployment/src/main/java/io/quarkiverse/operatorsdk/common/DependentResourceAugmentedClassInfo.java
This can be done implicitly using an activation condition that derives
from CRDPresentActivationCondition or explicitly using
the CSVMetadata.Optional annotation.
Fixes #1154
> feat: make it possible to mark dependents as optional
